### ISSUE TITLE
thrift 生成的代码不支持py3

### ISSUE THREAD

**Issue by liuhao2050** [XiaoMi/galaxy-sdk-python#1]

**Comment by a-whitej** [comment]
Same issue.

Traceback (most recent call last):
    from sds.auth.ttypes import Credential
  File "E:\Anaconda3\lib\site-packages\sds\auth\ttypes.py", line 11, in <module>
    import sds.errors.ttypes
  File "E:\Anaconda3\lib\site-packages\sds\errors\ttypes.py", line 12, in <module>
    from thrift.transport import TTransport
  File "E:\Anaconda3\lib\site-packages\thrift\transport\TTransport.py", line 20, in <module>
    from cStringIO import StringIO
ImportError: No module named 'cStringIO'

**Comment by hanjiacheng** [comment]
py3中无cStringIO库，改为：from io import StringIO
